<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>inc</string>
		<string>vpl</string>
	</array>
	<key>name</key>
	<string>VPL (LogicIO RTCU)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#conditional-compilation</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#vpl-keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#vpl-sfl-keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#vpl-psf-keywords</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.vpl</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\/\/).*$</string>
					<key>name</key>
					<string>comment.line.vpl</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.vpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*\/</string>
					<key>name</key>
					<string>comment.block.vpl</string>
				</dict>
			</array>
		</dict>
		<key>conditional-compilation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.define.value.vpl</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\#DEFINE(.*)$</string>
					<key>name</key>
					<string>keyword.define.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\#UNDEFINE</string>
					<key>name</key>
					<string>keyword.undefine.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\#IFDEF</string>
					<key>name</key>
					<string>keyword.ifdef.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\#END_IF</string>
					<key>name</key>
					<string>keyword.endif.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\#ELSE</string>
					<key>name</key>
					<string>keyword.else.vpl</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.vpl</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\"([^"]*)\"</string>
					<key>name</key>
					<string>string.quoted.double.vpl</string>
				</dict>
			</array>
		</dict>
		<key>vpl-keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(ACCESS|ADDR|ALIGN|AND|ARRAY|ASYNC|AUTO|BEGIN|BOOL|BY|CASE|CHANNEL|CLASS|CONFIG|CONFIGURATION|CONSTANT|DINT|DO|(DYNAMIC)|ELSE|ELSIF|END|END_CASE|END_FOR|END_FUNCTION|END_FUNCTION_BLOCK|END_IF|END_PROGRAM|END_REPEAT|END_STRUCT_BLOCK|END_TASK|END_THREAD_BLOCK|END_VAR|END_WHILE|EXIT|EXTCALL|F_EDGE|FALSE|FILE|FLOAT|FLOATB|FOR|FUNCTION|FUNCTION_BLOCK|GOTO|HIDE|IF|IMAGE|INCLUDE|INT|INTERVAL|LABEL|__LINE__|MOD|MUTABLE|MUTEX|__NOP__|NOT|NOAUTOCALC|OF|OFF|ON|OR|PRIORITY|PROGRAM|PTR|R_EDGE|REPEAT|RETURN|SCAN|SEMAPHORE|SINT|SIZEOF|STRING|STRUCT_BLOCK|TASK|THEN|THREAD_BLOCK|TO|TRUE|UNTIL|UPDATEIO|UPDATEOUT|VAR|VAR_INPUT|VAR_OUTPUT|VOICE|WHILE|XOR)\b</string>
					<key>name</key>
					<string>keyword.reserved.vpl</string>
				</dict>
			</array>
		</dict>
		<key>vpl-psf-keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(accOpen|accClose|accVector|accVectorToForce|accVectorToAngles|accWaitEvent|accSetAccelerationEvent|accAccelerationEvent|accSetShockEvent|accShockEvent|accLoggerSetConfig|accLoggerGetConfig|accLoggerStart|accLoggerStop|accLoggerLevel|accLoggerRead|accLoggerToMem)\b</string>
					<key>name</key>
					<string>keyword.psf.accelerometer.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(batChargerEnable|batIsCharging|batVoltageIsLow|batModuleMounted|batSimpleCharger|batChargerVoltage|batPowerLevel|batConsumption|batConsumptionAvg|batConsumptionClear|batConsumptionEnable|batConsumptionTotal)\b</string>
					<key>name</key>
					<string>keyword.psf.battery.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(boardSupplyVoltage|boardSupplyType|boardTemperature|boardVersion|boardType|boardSerialNumber|boardReset|boardGetProfile|boardGetProfileX|boardGetStatistics|boardWatchdog|boardSetPassword|boardSetPasswordAlt|boardClearPassword|boardSetFaultReset|boardBuzzer|boardBuzzerFrequency|boardDCOut|boardDCOut2|boardSetServicePortAlt|boardFaultLogGet|boardFaultLogGetDebug|boardFaultLogClear|boardEnableS0|boardSetOption|boardRequestOption)\b</string>
					<key>name</key>
					<string>keyword.psf.board.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(btOpen|btClose|btIsOpen|btSearch|btGetDeviceAddress|btGetDeviceName|btGetDeviceType|btConnect|btListen|btDisconnect|btConnection|btSignalLevel|btSendData|btReceiveData|btSetPin|btHsOpen|btHsClose|btHsConnected|btHsRingAccept|btHsRingReject|btPairClear|btPairClearAll|btSetLED)\b</string>
					<key>name</key>
					<string>keyword.psf.bluetooth.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(camOpen|camClose|camPresent|camSnapshot|camSnapshotToFile)\b</string>
					<key>name</key>
					<string>keyword.psf.camera.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(canOpen|canClose|canLoopBackMode|canSendMessage|canReceiveMessage|canFilterCreate|canFilterCreateOnce|canFilterCreateX|canFilterDestroy|canFilterStatus|canFlush|canBufferLevel|canLoggerSetup|canLoggerStart|canLoggerStop|canLoggerLevel|canLoggerRead|canLoggerToMemory|canFMSFilterCreate|canFMSGetPGN)\b</string>
					<key>name</key>
					<string>keyword.psf.can.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(displayBox|displayCircle|displayClear|displayDefineChar|displayGetKey|displayImage|displayLine|displayNumber|displayPoint|displayPower|displayString|displayXY)\b</string>
					<key>name</key>
					<string>keyword.psf.display.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(dtmfGetKey|dtmfGetNumber)\b</string>
					<key>name</key>
					<string>keyword.psf.dtmf.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(ethOpen|ethClose|ethPresent|ethConnect|ethConnection|ethDisconnect|ethSend|ethReceive)\b</string>
					<key>name</key>
					<string>keyword.psf.ethernet.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(fsMediaPresent|fsMediaWriteProtected|fsMediaOpen|fsMediaClose|fsMediaQuickFormat|fsMediaEject|fsStatusLEDEnable|fsDirCreate|fsDirChange|fsDirCurrent|fsDirCatalog|fsDirDelete|fsFileCreate|fsFileOpen|fsFileExists|fsFileRename|fsFileMove|fsFileDelete|fsFileStatus|fsFileGetCreateTime|fsFileGetSize|fsFileSeek|fsFilePosition|fsFileRead|fsFileReadString|fsFileWrite|fsFileWriteString|fsFileWriteStringNL|fsFileClose|fsFileFlush)\b</string>
					<key>name</key>
					<string>keyword.psf.filesystem.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(ftpOpen|ftpClose|ftpConnect|ftpConnected|ftpDisconnect|ftpCancel|ftpLastResponse|ftpDirChange|ftpDirCreate|ftpDirCurrent|ftpDirDelete|ftpDirRename|ftpDirCatalogGet|ftpDirCatalog|ftpFileDelete|ftpFileReceive|ftpFileRename|ftpFileSend|ftpFileSize)\b</string>
					<key>name</key>
					<string>keyword.psf.ftp.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(gwConnected|sockSetGWParm|sockGetGWParm|gwEnabled|gwPacketMode|gwReceivePacket|gwReceivePacketDone|gwSendPacket|gwSetMedia|gwTimeGet)\b</string>
					<key>name</key>
					<string>keyword.psf.gateway.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(gprsOpen|gprsClose|gprsConnected|gprsSetModemInit|gprsGetMonitorParm|gprsSetMonitorParm)\b</string>
					<key>name</key>
					<string>keyword.psf.gprs.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(gpsPower|gpsFix|gpsPointInPolygon|gpsEnableNMEA|gpsDistance|gpsDistanceX|gpsGetAntennaStatus|gpsNMEA|gpsSetSBAS|gpsGetSBAS|gpsSetSpeedThreshold|gpsUpdateFreq|gpsPositionToUtm|gpsUtmToPosition|gpsSemicircleToUtm|gpsUtmToSemicircle)\b</string>
					<key>name</key>
					<string>keyword.psf.gps.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(gsmAnswer|gsmOffHook|gsmHangup|gsmIncomingCall|gsmIncomingSMS|gsmConnected|gsmSendSMS|gsmMakeCall|gsmMakeCallX|gsmPower|gsmPowerLP|gsmSetAntennaMode|gsmSignalLevel|gsmSendPDU|gsmIncomingPDU|gsmSetListOfCallers|gsmGetListOfCallers|gsmGetIMEI|gsmGetIMSI|gsmGetICCID|gsmSendDTMF|gsmGetProviderList|gsmSetProvider|gsmSetPIN|gsmSetSMSSCN|gsmHeadset|gsmCheckSMS|gsmGetLAC|gsmGetCellID|gsmGetStatus|gsmGetCurrentProvider|gsmGetHomeProvider|gsmSIMPresent|gsmSIMLocked|gsmModemMode|gsmSendFlashSMS|gsmSimSetPIN|gsmNetworkTime)\b</string>
					<key>name</key>
					<string>keyword.psf.gsm.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(mdtOpen|mdtPower|mdtStandby|mdtWrite|mdtGotoXY|mdtCurrentX|mdtCurrentY|mdtScrollDown|mdtScrollUp|mdtGetKey|mdtClear|mdtClearLine|mdtCursor|mdtBacklight|mdtBeep|mdtContrast|mdtDefineChar|mdtProfile)\b</string>
					<key>name</key>
					<string>keyword.psf.mobile.data.terminal.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(Sleep|DeepSleep|PowerDown|HostConnected|memioWrite|memioRead|memioWriteX|memioReadX)\b</string>
					<key>name</key>
					<string>keyword.psf.misc.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(ioDeviceEnable|ioGetStatus|ioSetMode|ioSynchronize|ioWaitException|modbusOpen|modbusReceive|modbusSend|modbusWaitData)\b</string>
					<key>name</key>
					<string>keyword.psf.modbus.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(mqttOpen|mqttClose|mqttIsConnected|mqttStatus|mqttPublish|mqttSubscribe|mqttUnsubscribe|mqttWaiEvent|mqttReceive)\b</string>
					<key>name</key>
					<string>keyword.psf.mqtt.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(navOpen|navClose|navPresent|navVersion|navGetAPILevel|navDeviceSerial|navWaitEvent|navSetUIText|navDeleteData|navFix|navUserIDAuthenticate|navUserIDReceive|navUserIDReceiveX|navUserIDRequest|navUserIDSet|navUserStatusDefine|navUserStatusDelete|navUserStatusReceive|navUserStatusRcvX|navUserStatusRequest|navUserStatusSet|navMessageSend|navMessageDelete|navMessageStatusReceive|navMessageStatusRequest|navMessageReceive|navMessageReceiveX|navMessageQuickDefine|navMessageQuickDelete|navMessageReplyDefine|navMessageReplyDelete|navMessageReplyReceive|navStopSet|navStopReceive|navStopRequest|navStopSort|navStopIndexSet|navStopSetActive|navStopSetDone|navStopDelete|navAutoArrival|navETAReceive|navETARequest|navETAAutoSet|navGPITransfer|navGPIProgressReceive|navGPIRequestID|navGPIReceiveID|navWaypointSet|navWaypointDelete|navWaypointDeleteByCat|navPositionToSemicircles|navSemicirclesToPosition)\b</string>
					<key>name</key>
					<string>keyword.psf.navigation.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(nmpPresent|nmpUpdate|nmpUpdateProgressReceive|nmpPower|nmpStopPopup|nmpStopClose|nmpPlaySound|nmpShowDialog|nmpRemoveDialog|nmpDialogClickReceive|nmpGetHardwareID|nmpHideMenus|nmpHomePos|nmpSetVolume|nmpLCDBrightness|nmpSetLED|nmpHardwareButtonsEnable|nmpHardwareButtonPressedReceive|nmpCameraOpen|nmpCameraClose|nmpRGBToDint|nmpButtonsDefine|nmpButtonCreate|nmpButtonEnable|nmpButtonVisible|nmpButtonWidth|nmpButtonColor|nmpButtonText|nmpButtonFlash|nmpButtonConfirm|nmpButtonPressedReceive)\b</string>
					<key>name</key>
					<string>keyword.psf.nmp.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(owSearch|owTempGetID|owTempGet|owiButtonGetID|owiButtonReadData|owiButtonWriteData|owiButtonEnableLED|owiButtonSetLed|owSearchX|owQuery|owGetID|owGetFamily|owAccess|owRelease|owReadData|owWriteData|owRead|owReadBit|owWrite|owWriteBit|owAlarmSearch|owAlarmQuery|owAlarmGetID|owAlarmGetFamily|owAlarmAccess|owAlarmRelease)\b</string>
					<key>name</key>
					<string>keyword.psf.onewire.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(pmPowerDown|pmDeepSleep|pmPowerFail|pmWaitEvent|pmSetVibrationsensitivity|pmVibration|pmSetSpeed)\b</string>
					<key>name</key>
					<string>keyword.psf.power.management.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(rfOpen|rfClose|rfReceive|rfSend|rfSetPower)\b</string>
					<key>name</key>
					<string>keyword.psf.rf.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(rfbcPresent|rfbcOpen|rfbcClose|rfbcGetConfig|rfbcSetConfig|rfbcWaitEvent|rfbcPairRequestReceive|rfbcRawEventReceive|rfbcRawFilter|rfbcRawSend|rfbcRemoteControlEventReceive|rfbcSwitchEventReceive|rfbcTemperatureEventReceive|rfbcSensorEventReceive|rfbcSendAck|rfbcSendButtonPress|rfbcSetSwitchState)\b</string>
					<key>name</key>
					<string>keyword.psf.rfbc.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(serOpen|serClose|serSendChar|serSendString|serSendData|serFrameReceiver|serFrameReceiveDone|serFlush|serForceDataReady|serSetHandshake|serGetBufferLevel|serGetCTS|serSetRTS)\b</string>
					<key>name</key>
					<string>keyword.psf.serial.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(smtpOpen|smtpClose|smtpSetConfig|smtpGetConfig|smtpSend|smtpNew|smtpAddText|smtpAddAttachment|smtpSendX|smtpCancel|smtpStatus|smtpAwaitCompletion)\b</string>
					<key>name</key>
					<string>keyword.psf.smtp.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(sockConnect|sockConnection|sockDisconnect|sockGetLocalIP|sockIPFromName|sockIPToName|sockListen|sockReceive|sockSend|sockSetTCPIPParm|sockGetTCPIPParm)\b</string>
					<key>name</key>
					<string>keyword.psf.socket.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(udpStartListen|udpStopListen|udpReceive|udpSend)\b</string>
					<key>name</key>
					<string>keyword.psf.udp.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(verSetAppProfile|verGetAppVersion|verGetAppName|verCheckUpgrade)\b</string>
					<key>name</key>
					<string>keyword.psf.version.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(voiceTalk|voiceStop|voiceBusy)\b</string>
					<key>name</key>
					<string>keyword.psf.voice.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(zpPowerDown|zpBootEvent)\b</string>
					<key>name</key>
					<string>keyword.psf.zero.power.vpl</string>
				</dict>
			</array>
		</dict>
		<key>vpl-sfl-keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(shr32|shr16|shr8|shl32|shl16|shl8|bcd_to_sint|bcd_to_int|bcd_to_dint|sint_to_bcd|int_to_bcd|dint_to_bcd)\b</string>
					<key>name</key>
					<string>keyword.sfl.binary.operation.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(abs|min|max|VolumeHorizontalTank|VolumeVerticalTank|CRC16|crcCalculate|random|calcPow|rdDecrypt128|rdEncrypt128)\b</string>
					<key>name</key>
					<string>keyword.sfl.calculation.routines.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(chInit|chDestroy|chStatus|chRead|chWrite|chPeek)\b</string>
					<key>name</key>
					<string>keyword.sfl.channel.functions.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(CTD|CTU|CTUD|PCT)\b</string>
					<key>name</key>
					<string>keyword.sfl.counter.function.blocks.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(logInitialize|logClear|logNext|logPrev|logFirst|logLast|logNumOfRecords|logMaxNumOfRecords|logValuesPerRecord|logIsInitialized|logWrite|logReWrite|logReWriteTag|logRead|logDestroy|logGotoLinsec|logSeek)\b</string>
					<key>name</key>
					<string>keyword.sfl.datalogger.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(DebugMsg|DebugFmt)\b</string>
					<key>name</key>
					<string>keyword.sfl.debugger.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(R_TRIG|F_TRIG|RF_TRIG)\b</string>
					<key>name</key>
					<string>keyword.sfl.edge.triggers.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(cos|acos|sin|asin|tan|atan|atan2)\b</string>
					<key>name</key>
					<string>keyword.sfl.math.trig.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(exp|exp2|frexp|ldexp|log|log2|log10|modf|sqrt)\b</string>
					<key>name</key>
					<string>keyword.sfl.math.log.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(ceil|floor)\b</string>
					<key>name</key>
					<string>keyword.sfl.math.round.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(fabs|fmin|fmax|IsInf|IsNaN)\b</string>
					<key>name</key>
					<string>keyword.sfl.math.other.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(floatToStr|strToFloat|degToRad|radToDeg|degToPosition|positionToDeg)\b</string>
					<key>name</key>
					<string>keyword.sfl.math.conversion.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(Debounce|memcpy|RS|SR)\b</string>
					<key>name</key>
					<string>keyword.sfl.misc.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(mxInit|mxDestroy|mxStatus|mxLock|mxUnlock)\b</string>
					<key>name</key>
					<string>keyword.sfl.mutex.functions.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(SaveString|LoadString|SaveData|LoadData|SaveStringF|LoadStringF|SaveDataF|LoadDataF|SaveStringX|LoadStringX|SaveDataX|LoadDataX|GetFlashXSize)\b</string>
					<key>name</key>
					<string>keyword.sfl.persistent.memory.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(clockGet|clockNow|clockSet|clockTimeToLinsec|clockLinsecToTime|clockAlarm|clockDayTimer|clockWeekTimer)\b</string>
					<key>name</key>
					<string>keyword.sfl.real.time.clock.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(semInit|semDestroy|semWait|semSignal|semValue)\b</string>
					<key>name</key>
					<string>keyword.sfl.semaphore.functions.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(strFormat|strGetValues|strGetStrings|strToInt|strToDint|strToSint|strCompare|strConcat|strLeft|strRight|strMid|strLen|strLookup|strFind|strToken|strRemoveSpaces|sintToStr|intToStr|dintToStr|strToMemory|strFromMemory|strEncode64|strDecode64|strMemoryUsage)\b</string>
					<key>name</key>
					<string>keyword.sfl.string.handling.functions.vpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(TOF|TON|TP|TPERIOD)\b</string>
					<key>name</key>
					<string>keyword.sfl.timer.functions.vpl</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.vpl</string>
	<key>uuid</key>
	<string>705d1522-e018-4330-873d-9297777000d7</string>
</dict>
</plist>
